//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Admin.SNS.Categories {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblCategoryId;
	protected global::System.Web.UI.WebControls.Label lblName;
	protected global::System.Web.UI.WebControls.Label lblDescription;
	protected global::System.Web.UI.WebControls.Label lblParentID;
	protected global::System.Web.UI.WebControls.Label lblPath;
	protected global::System.Web.UI.WebControls.Label lblDepth;
	protected global::System.Web.UI.WebControls.Label lblSequence;
	protected global::System.Web.UI.WebControls.Label lblHasChildren;
	protected global::System.Web.UI.WebControls.Label lblIsMenu;
	protected global::System.Web.UI.WebControls.Label lblType;
	protected global::System.Web.UI.WebControls.Label lblMenuIsShow;
	protected global::System.Web.UI.WebControls.Label lblMenuSequence;
	protected global::System.Web.UI.WebControls.Label lblCreatedUserID;
	protected global::System.Web.UI.WebControls.Label lblCreatedDate;
	protected global::System.Web.UI.WebControls.Label lblStatus;


       
    }
}
