//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Services.JZService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.nineorange.com", ConfigurationName="JZService.BusinessService")]
    public interface BusinessService {
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Maticsoft.Services.JZService.getReceivedMsgResponse getReceivedMsg(Maticsoft.Services.JZService.getReceivedMsg request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.getReceivedMsgResponse> getReceivedMsgAsync(Maticsoft.Services.JZService.getReceivedMsg request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Maticsoft.Services.JZService.sendBatchMessageTimelyExtResponse sendBatchMessageTimelyExt(Maticsoft.Services.JZService.sendBatchMessageTimelyExt request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendBatchMessageTimelyExtResponse> sendBatchMessageTimelyExtAsync(Maticsoft.Services.JZService.sendBatchMessageTimelyExt request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Maticsoft.Services.JZService.sendPersonalMessagesResponse sendPersonalMessages(Maticsoft.Services.JZService.sendPersonalMessages request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendPersonalMessagesResponse> sendPersonalMessagesAsync(Maticsoft.Services.JZService.sendPersonalMessages request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Maticsoft.Services.JZService.modifyPasswordResponse modifyPassword(Maticsoft.Services.JZService.modifyPassword request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.modifyPasswordResponse> modifyPasswordAsync(Maticsoft.Services.JZService.modifyPassword request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Maticsoft.Services.JZService.getReceiptResponse getReceipt(Maticsoft.Services.JZService.getReceipt request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.getReceiptResponse> getReceiptAsync(Maticsoft.Services.JZService.getReceipt request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Maticsoft.Services.JZService.sendBatchMessageResponse sendBatchMessage(Maticsoft.Services.JZService.sendBatchMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendBatchMessageResponse> sendBatchMessageAsync(Maticsoft.Services.JZService.sendBatchMessage request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Maticsoft.Services.JZService.sendGjBatchMessageResponse sendGjBatchMessage(Maticsoft.Services.JZService.sendGjBatchMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendGjBatchMessageResponse> sendGjBatchMessageAsync(Maticsoft.Services.JZService.sendGjBatchMessage request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Maticsoft.Services.JZService.validateUserResponse validateUser(Maticsoft.Services.JZService.validateUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.validateUserResponse> validateUserAsync(Maticsoft.Services.JZService.validateUser request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Maticsoft.Services.JZService.sendMessageResponse sendMessage(Maticsoft.Services.JZService.sendMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendMessageResponse> sendMessageAsync(Maticsoft.Services.JZService.sendMessage request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Maticsoft.Services.JZService.sendTimelyMessageResponse sendTimelyMessage(Maticsoft.Services.JZService.sendTimelyMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendTimelyMessageResponse> sendTimelyMessageAsync(Maticsoft.Services.JZService.sendTimelyMessage request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Maticsoft.Services.JZService.sendMmsMessagesResponse sendMmsMessages(Maticsoft.Services.JZService.sendMmsMessages request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendMmsMessagesResponse> sendMmsMessagesAsync(Maticsoft.Services.JZService.sendMmsMessages request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Maticsoft.Services.JZService.gxmtResponse gxmt(Maticsoft.Services.JZService.gxmt request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.gxmtResponse> gxmtAsync(Maticsoft.Services.JZService.gxmt request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Maticsoft.Services.JZService.getUserInfoResponse getUserInfo(Maticsoft.Services.JZService.getUserInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.getUserInfoResponse> getUserInfoAsync(Maticsoft.Services.JZService.getUserInfo request);
        
        // CODEGEN: 命名空间 http://service.nineorange.com 的元素名称 account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Maticsoft.Services.JZService.sendAudioResponse sendAudio(Maticsoft.Services.JZService.sendAudio request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendAudioResponse> sendAudioAsync(Maticsoft.Services.JZService.sendAudio request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReceivedMsg {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReceivedMsg", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.getReceivedMsgBody Body;
        
        public getReceivedMsg() {
        }
        
        public getReceivedMsg(Maticsoft.Services.JZService.getReceivedMsgBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getReceivedMsgBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int param;
        
        public getReceivedMsgBody() {
        }
        
        public getReceivedMsgBody(string account, string password, int param) {
            this.account = account;
            this.password = password;
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReceivedMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReceivedMsgResponse", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.getReceivedMsgResponseBody Body;
        
        public getReceivedMsgResponse() {
        }
        
        public getReceivedMsgResponse(Maticsoft.Services.JZService.getReceivedMsgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getReceivedMsgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getReceivedMsgReturn;
        
        public getReceivedMsgResponseBody() {
        }
        
        public getReceivedMsgResponseBody(string getReceivedMsgReturn) {
            this.getReceivedMsgReturn = getReceivedMsgReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendBatchMessageTimelyExt {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendBatchMessageTimelyExt", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.sendBatchMessageTimelyExtBody Body;
        
        public sendBatchMessageTimelyExt() {
        }
        
        public sendBatchMessageTimelyExt(Maticsoft.Services.JZService.sendBatchMessageTimelyExtBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendBatchMessageTimelyExtBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sendDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destmobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msgText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ext;
        
        public sendBatchMessageTimelyExtBody() {
        }
        
        public sendBatchMessageTimelyExtBody(string account, string password, string sendDateTime, string destmobile, string msgText, string ext) {
            this.account = account;
            this.password = password;
            this.sendDateTime = sendDateTime;
            this.destmobile = destmobile;
            this.msgText = msgText;
            this.ext = ext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendBatchMessageTimelyExtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendBatchMessageTimelyExtResponse", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.sendBatchMessageTimelyExtResponseBody Body;
        
        public sendBatchMessageTimelyExtResponse() {
        }
        
        public sendBatchMessageTimelyExtResponse(Maticsoft.Services.JZService.sendBatchMessageTimelyExtResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendBatchMessageTimelyExtResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public sendBatchMessageTimelyExtResponseBody() {
        }
        
        public sendBatchMessageTimelyExtResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendPersonalMessages {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendPersonalMessages", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.sendPersonalMessagesBody Body;
        
        public sendPersonalMessages() {
        }
        
        public sendPersonalMessages(Maticsoft.Services.JZService.sendPersonalMessagesBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendPersonalMessagesBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string destMobiles;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msgContents;
        
        public sendPersonalMessagesBody() {
        }
        
        public sendPersonalMessagesBody(string account, string password, string destMobiles, string msgContents) {
            this.account = account;
            this.password = password;
            this.destMobiles = destMobiles;
            this.msgContents = msgContents;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendPersonalMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendPersonalMessagesResponse", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.sendPersonalMessagesResponseBody Body;
        
        public sendPersonalMessagesResponse() {
        }
        
        public sendPersonalMessagesResponse(Maticsoft.Services.JZService.sendPersonalMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendPersonalMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendPersonalMessagesReturn;
        
        public sendPersonalMessagesResponseBody() {
        }
        
        public sendPersonalMessagesResponseBody(int sendPersonalMessagesReturn) {
            this.sendPersonalMessagesReturn = sendPersonalMessagesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modifyPassword {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modifyPassword", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.modifyPasswordBody Body;
        
        public modifyPassword() {
        }
        
        public modifyPassword(Maticsoft.Services.JZService.modifyPasswordBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class modifyPasswordBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newPassword;
        
        public modifyPasswordBody() {
        }
        
        public modifyPasswordBody(string account, string oldPassword, string newPassword) {
            this.account = account;
            this.oldPassword = oldPassword;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modifyPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modifyPasswordResponse", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.modifyPasswordResponseBody Body;
        
        public modifyPasswordResponse() {
        }
        
        public modifyPasswordResponse(Maticsoft.Services.JZService.modifyPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class modifyPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int modifyPasswordReturn;
        
        public modifyPasswordResponseBody() {
        }
        
        public modifyPasswordResponseBody(int modifyPasswordReturn) {
            this.modifyPasswordReturn = modifyPasswordReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReceipt {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReceipt", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.getReceiptBody Body;
        
        public getReceipt() {
        }
        
        public getReceipt(Maticsoft.Services.JZService.getReceiptBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getReceiptBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int taskID;
        
        public getReceiptBody() {
        }
        
        public getReceiptBody(string account, string password, int taskID) {
            this.account = account;
            this.password = password;
            this.taskID = taskID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReceiptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReceiptResponse", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.getReceiptResponseBody Body;
        
        public getReceiptResponse() {
        }
        
        public getReceiptResponse(Maticsoft.Services.JZService.getReceiptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getReceiptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getReceiptReturn;
        
        public getReceiptResponseBody() {
        }
        
        public getReceiptResponseBody(string getReceiptReturn) {
            this.getReceiptReturn = getReceiptReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendBatchMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendBatchMessage", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.sendBatchMessageBody Body;
        
        public sendBatchMessage() {
        }
        
        public sendBatchMessage(Maticsoft.Services.JZService.sendBatchMessageBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendBatchMessageBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string destmobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msgText;
        
        public sendBatchMessageBody() {
        }
        
        public sendBatchMessageBody(string account, string password, string destmobile, string msgText) {
            this.account = account;
            this.password = password;
            this.destmobile = destmobile;
            this.msgText = msgText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendBatchMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendBatchMessageResponse", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.sendBatchMessageResponseBody Body;
        
        public sendBatchMessageResponse() {
        }
        
        public sendBatchMessageResponse(Maticsoft.Services.JZService.sendBatchMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendBatchMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendBatchMessageReturn;
        
        public sendBatchMessageResponseBody() {
        }
        
        public sendBatchMessageResponseBody(int sendBatchMessageReturn) {
            this.sendBatchMessageReturn = sendBatchMessageReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendGjBatchMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendGjBatchMessage", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.sendGjBatchMessageBody Body;
        
        public sendGjBatchMessage() {
        }
        
        public sendGjBatchMessage(Maticsoft.Services.JZService.sendGjBatchMessageBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendGjBatchMessageBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sendDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destmobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msgText;
        
        public sendGjBatchMessageBody() {
        }
        
        public sendGjBatchMessageBody(string account, string password, string sendDateTime, string destmobile, string msgText) {
            this.account = account;
            this.password = password;
            this.sendDateTime = sendDateTime;
            this.destmobile = destmobile;
            this.msgText = msgText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendGjBatchMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendGjBatchMessageResponse", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.sendGjBatchMessageResponseBody Body;
        
        public sendGjBatchMessageResponse() {
        }
        
        public sendGjBatchMessageResponse(Maticsoft.Services.JZService.sendGjBatchMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendGjBatchMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public sendGjBatchMessageResponseBody() {
        }
        
        public sendGjBatchMessageResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateUser", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.validateUserBody Body;
        
        public validateUser() {
        }
        
        public validateUser(Maticsoft.Services.JZService.validateUserBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class validateUserBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public validateUserBody() {
        }
        
        public validateUserBody(string account, string password) {
            this.account = account;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateUserResponse", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.validateUserResponseBody Body;
        
        public validateUserResponse() {
        }
        
        public validateUserResponse(Maticsoft.Services.JZService.validateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class validateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int validateUserReturn;
        
        public validateUserResponseBody() {
        }
        
        public validateUserResponseBody(int validateUserReturn) {
            this.validateUserReturn = validateUserReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMessage", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.sendMessageBody Body;
        
        public sendMessage() {
        }
        
        public sendMessage(Maticsoft.Services.JZService.sendMessageBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendMessageBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string destmobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msgText;
        
        public sendMessageBody() {
        }
        
        public sendMessageBody(string account, string password, string destmobile, string msgText) {
            this.account = account;
            this.password = password;
            this.destmobile = destmobile;
            this.msgText = msgText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMessageResponse", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.sendMessageResponseBody Body;
        
        public sendMessageResponse() {
        }
        
        public sendMessageResponse(Maticsoft.Services.JZService.sendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendMessageReturn;
        
        public sendMessageResponseBody() {
        }
        
        public sendMessageResponseBody(int sendMessageReturn) {
            this.sendMessageReturn = sendMessageReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendTimelyMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendTimelyMessage", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.sendTimelyMessageBody Body;
        
        public sendTimelyMessage() {
        }
        
        public sendTimelyMessage(Maticsoft.Services.JZService.sendTimelyMessageBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendTimelyMessageBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sendDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destmobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msgText;
        
        public sendTimelyMessageBody() {
        }
        
        public sendTimelyMessageBody(string account, string password, string sendDateTime, string destmobile, string msgText) {
            this.account = account;
            this.password = password;
            this.sendDateTime = sendDateTime;
            this.destmobile = destmobile;
            this.msgText = msgText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendTimelyMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendTimelyMessageResponse", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.sendTimelyMessageResponseBody Body;
        
        public sendTimelyMessageResponse() {
        }
        
        public sendTimelyMessageResponse(Maticsoft.Services.JZService.sendTimelyMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendTimelyMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendTimelyMessageReturn;
        
        public sendTimelyMessageResponseBody() {
        }
        
        public sendTimelyMessageResponseBody(int sendTimelyMessageReturn) {
            this.sendTimelyMessageReturn = sendTimelyMessageReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMmsMessages {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMmsMessages", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.sendMmsMessagesBody Body;
        
        public sendMmsMessages() {
        }
        
        public sendMmsMessages(Maticsoft.Services.JZService.sendMmsMessagesBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendMmsMessagesBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string phones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mmsString;
        
        public sendMmsMessagesBody() {
        }
        
        public sendMmsMessagesBody(string account, string password, string phones, string mmsString) {
            this.account = account;
            this.password = password;
            this.phones = phones;
            this.mmsString = mmsString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMmsMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMmsMessagesResponse", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.sendMmsMessagesResponseBody Body;
        
        public sendMmsMessagesResponse() {
        }
        
        public sendMmsMessagesResponse(Maticsoft.Services.JZService.sendMmsMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendMmsMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendMmsMessagesReturn;
        
        public sendMmsMessagesResponseBody() {
        }
        
        public sendMmsMessagesResponseBody(int sendMmsMessagesReturn) {
            this.sendMmsMessagesReturn = sendMmsMessagesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class gxmt {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="gxmt", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.gxmtBody Body;
        
        public gxmt() {
        }
        
        public gxmt(Maticsoft.Services.JZService.gxmtBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class gxmtBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sendDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destmobiles;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msgTexts;
        
        public gxmtBody() {
        }
        
        public gxmtBody(string account, string password, string sendDateTime, string destmobiles, string msgTexts) {
            this.account = account;
            this.password = password;
            this.sendDateTime = sendDateTime;
            this.destmobiles = destmobiles;
            this.msgTexts = msgTexts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class gxmtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="gxmtResponse", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.gxmtResponseBody Body;
        
        public gxmtResponse() {
        }
        
        public gxmtResponse(Maticsoft.Services.JZService.gxmtResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class gxmtResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int gxmtReturn;
        
        public gxmtResponseBody() {
        }
        
        public gxmtResponseBody(int gxmtReturn) {
            this.gxmtReturn = gxmtReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserInfo", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.getUserInfoBody Body;
        
        public getUserInfo() {
        }
        
        public getUserInfo(Maticsoft.Services.JZService.getUserInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getUserInfoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public getUserInfoBody() {
        }
        
        public getUserInfoBody(string account, string password) {
            this.account = account;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserInfoResponse", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.getUserInfoResponseBody Body;
        
        public getUserInfoResponse() {
        }
        
        public getUserInfoResponse(Maticsoft.Services.JZService.getUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class getUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUserInfoReturn;
        
        public getUserInfoResponseBody() {
        }
        
        public getUserInfoResponseBody(string getUserInfoReturn) {
            this.getUserInfoReturn = getUserInfoReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendAudio {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendAudio", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.sendAudioBody Body;
        
        public sendAudio() {
        }
        
        public sendAudio(Maticsoft.Services.JZService.sendAudioBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendAudioBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sendDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string destmobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msgText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string srcMobile;
        
        public sendAudioBody() {
        }
        
        public sendAudioBody(string account, string password, string sendDateTime, string destmobile, string msgText, string srcMobile) {
            this.account = account;
            this.password = password;
            this.sendDateTime = sendDateTime;
            this.destmobile = destmobile;
            this.msgText = msgText;
            this.srcMobile = srcMobile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendAudioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendAudioResponse", Namespace="http://service.nineorange.com", Order=0)]
        public Maticsoft.Services.JZService.sendAudioResponseBody Body;
        
        public sendAudioResponse() {
        }
        
        public sendAudioResponse(Maticsoft.Services.JZService.sendAudioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.nineorange.com")]
    public partial class sendAudioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public sendAudioResponseBody() {
        }
        
        public sendAudioResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BusinessServiceChannel : Maticsoft.Services.JZService.BusinessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusinessServiceClient : System.ServiceModel.ClientBase<Maticsoft.Services.JZService.BusinessService>, Maticsoft.Services.JZService.BusinessService {
        
        public BusinessServiceClient() {
        }
        
        public BusinessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusinessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maticsoft.Services.JZService.getReceivedMsgResponse Maticsoft.Services.JZService.BusinessService.getReceivedMsg(Maticsoft.Services.JZService.getReceivedMsg request) {
            return base.Channel.getReceivedMsg(request);
        }
        
        public string getReceivedMsg(string account, string password, int param) {
            Maticsoft.Services.JZService.getReceivedMsg inValue = new Maticsoft.Services.JZService.getReceivedMsg();
            inValue.Body = new Maticsoft.Services.JZService.getReceivedMsgBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.param = param;
            Maticsoft.Services.JZService.getReceivedMsgResponse retVal = ((Maticsoft.Services.JZService.BusinessService)(this)).getReceivedMsg(inValue);
            return retVal.Body.getReceivedMsgReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.getReceivedMsgResponse> Maticsoft.Services.JZService.BusinessService.getReceivedMsgAsync(Maticsoft.Services.JZService.getReceivedMsg request) {
            return base.Channel.getReceivedMsgAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maticsoft.Services.JZService.getReceivedMsgResponse> getReceivedMsgAsync(string account, string password, int param) {
            Maticsoft.Services.JZService.getReceivedMsg inValue = new Maticsoft.Services.JZService.getReceivedMsg();
            inValue.Body = new Maticsoft.Services.JZService.getReceivedMsgBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.param = param;
            return ((Maticsoft.Services.JZService.BusinessService)(this)).getReceivedMsgAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maticsoft.Services.JZService.sendBatchMessageTimelyExtResponse Maticsoft.Services.JZService.BusinessService.sendBatchMessageTimelyExt(Maticsoft.Services.JZService.sendBatchMessageTimelyExt request) {
            return base.Channel.sendBatchMessageTimelyExt(request);
        }
        
        public int sendBatchMessageTimelyExt(string account, string password, string sendDateTime, string destmobile, string msgText, string ext) {
            Maticsoft.Services.JZService.sendBatchMessageTimelyExt inValue = new Maticsoft.Services.JZService.sendBatchMessageTimelyExt();
            inValue.Body = new Maticsoft.Services.JZService.sendBatchMessageTimelyExtBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            inValue.Body.ext = ext;
            Maticsoft.Services.JZService.sendBatchMessageTimelyExtResponse retVal = ((Maticsoft.Services.JZService.BusinessService)(this)).sendBatchMessageTimelyExt(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendBatchMessageTimelyExtResponse> Maticsoft.Services.JZService.BusinessService.sendBatchMessageTimelyExtAsync(Maticsoft.Services.JZService.sendBatchMessageTimelyExt request) {
            return base.Channel.sendBatchMessageTimelyExtAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendBatchMessageTimelyExtResponse> sendBatchMessageTimelyExtAsync(string account, string password, string sendDateTime, string destmobile, string msgText, string ext) {
            Maticsoft.Services.JZService.sendBatchMessageTimelyExt inValue = new Maticsoft.Services.JZService.sendBatchMessageTimelyExt();
            inValue.Body = new Maticsoft.Services.JZService.sendBatchMessageTimelyExtBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            inValue.Body.ext = ext;
            return ((Maticsoft.Services.JZService.BusinessService)(this)).sendBatchMessageTimelyExtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maticsoft.Services.JZService.sendPersonalMessagesResponse Maticsoft.Services.JZService.BusinessService.sendPersonalMessages(Maticsoft.Services.JZService.sendPersonalMessages request) {
            return base.Channel.sendPersonalMessages(request);
        }
        
        public int sendPersonalMessages(string account, string password, string destMobiles, string msgContents) {
            Maticsoft.Services.JZService.sendPersonalMessages inValue = new Maticsoft.Services.JZService.sendPersonalMessages();
            inValue.Body = new Maticsoft.Services.JZService.sendPersonalMessagesBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.destMobiles = destMobiles;
            inValue.Body.msgContents = msgContents;
            Maticsoft.Services.JZService.sendPersonalMessagesResponse retVal = ((Maticsoft.Services.JZService.BusinessService)(this)).sendPersonalMessages(inValue);
            return retVal.Body.sendPersonalMessagesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendPersonalMessagesResponse> Maticsoft.Services.JZService.BusinessService.sendPersonalMessagesAsync(Maticsoft.Services.JZService.sendPersonalMessages request) {
            return base.Channel.sendPersonalMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendPersonalMessagesResponse> sendPersonalMessagesAsync(string account, string password, string destMobiles, string msgContents) {
            Maticsoft.Services.JZService.sendPersonalMessages inValue = new Maticsoft.Services.JZService.sendPersonalMessages();
            inValue.Body = new Maticsoft.Services.JZService.sendPersonalMessagesBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.destMobiles = destMobiles;
            inValue.Body.msgContents = msgContents;
            return ((Maticsoft.Services.JZService.BusinessService)(this)).sendPersonalMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maticsoft.Services.JZService.modifyPasswordResponse Maticsoft.Services.JZService.BusinessService.modifyPassword(Maticsoft.Services.JZService.modifyPassword request) {
            return base.Channel.modifyPassword(request);
        }
        
        public int modifyPassword(string account, string oldPassword, string newPassword) {
            Maticsoft.Services.JZService.modifyPassword inValue = new Maticsoft.Services.JZService.modifyPassword();
            inValue.Body = new Maticsoft.Services.JZService.modifyPasswordBody();
            inValue.Body.account = account;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            Maticsoft.Services.JZService.modifyPasswordResponse retVal = ((Maticsoft.Services.JZService.BusinessService)(this)).modifyPassword(inValue);
            return retVal.Body.modifyPasswordReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.modifyPasswordResponse> Maticsoft.Services.JZService.BusinessService.modifyPasswordAsync(Maticsoft.Services.JZService.modifyPassword request) {
            return base.Channel.modifyPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maticsoft.Services.JZService.modifyPasswordResponse> modifyPasswordAsync(string account, string oldPassword, string newPassword) {
            Maticsoft.Services.JZService.modifyPassword inValue = new Maticsoft.Services.JZService.modifyPassword();
            inValue.Body = new Maticsoft.Services.JZService.modifyPasswordBody();
            inValue.Body.account = account;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            return ((Maticsoft.Services.JZService.BusinessService)(this)).modifyPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maticsoft.Services.JZService.getReceiptResponse Maticsoft.Services.JZService.BusinessService.getReceipt(Maticsoft.Services.JZService.getReceipt request) {
            return base.Channel.getReceipt(request);
        }
        
        public string getReceipt(string account, string password, int taskID) {
            Maticsoft.Services.JZService.getReceipt inValue = new Maticsoft.Services.JZService.getReceipt();
            inValue.Body = new Maticsoft.Services.JZService.getReceiptBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.taskID = taskID;
            Maticsoft.Services.JZService.getReceiptResponse retVal = ((Maticsoft.Services.JZService.BusinessService)(this)).getReceipt(inValue);
            return retVal.Body.getReceiptReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.getReceiptResponse> Maticsoft.Services.JZService.BusinessService.getReceiptAsync(Maticsoft.Services.JZService.getReceipt request) {
            return base.Channel.getReceiptAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maticsoft.Services.JZService.getReceiptResponse> getReceiptAsync(string account, string password, int taskID) {
            Maticsoft.Services.JZService.getReceipt inValue = new Maticsoft.Services.JZService.getReceipt();
            inValue.Body = new Maticsoft.Services.JZService.getReceiptBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.taskID = taskID;
            return ((Maticsoft.Services.JZService.BusinessService)(this)).getReceiptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maticsoft.Services.JZService.sendBatchMessageResponse Maticsoft.Services.JZService.BusinessService.sendBatchMessage(Maticsoft.Services.JZService.sendBatchMessage request) {
            return base.Channel.sendBatchMessage(request);
        }
        
        public int sendBatchMessage(string account, string password, string destmobile, string msgText) {
            Maticsoft.Services.JZService.sendBatchMessage inValue = new Maticsoft.Services.JZService.sendBatchMessage();
            inValue.Body = new Maticsoft.Services.JZService.sendBatchMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            Maticsoft.Services.JZService.sendBatchMessageResponse retVal = ((Maticsoft.Services.JZService.BusinessService)(this)).sendBatchMessage(inValue);
            return retVal.Body.sendBatchMessageReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendBatchMessageResponse> Maticsoft.Services.JZService.BusinessService.sendBatchMessageAsync(Maticsoft.Services.JZService.sendBatchMessage request) {
            return base.Channel.sendBatchMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendBatchMessageResponse> sendBatchMessageAsync(string account, string password, string destmobile, string msgText) {
            Maticsoft.Services.JZService.sendBatchMessage inValue = new Maticsoft.Services.JZService.sendBatchMessage();
            inValue.Body = new Maticsoft.Services.JZService.sendBatchMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            return ((Maticsoft.Services.JZService.BusinessService)(this)).sendBatchMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maticsoft.Services.JZService.sendGjBatchMessageResponse Maticsoft.Services.JZService.BusinessService.sendGjBatchMessage(Maticsoft.Services.JZService.sendGjBatchMessage request) {
            return base.Channel.sendGjBatchMessage(request);
        }
        
        public int sendGjBatchMessage(string account, string password, string sendDateTime, string destmobile, string msgText) {
            Maticsoft.Services.JZService.sendGjBatchMessage inValue = new Maticsoft.Services.JZService.sendGjBatchMessage();
            inValue.Body = new Maticsoft.Services.JZService.sendGjBatchMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            Maticsoft.Services.JZService.sendGjBatchMessageResponse retVal = ((Maticsoft.Services.JZService.BusinessService)(this)).sendGjBatchMessage(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendGjBatchMessageResponse> Maticsoft.Services.JZService.BusinessService.sendGjBatchMessageAsync(Maticsoft.Services.JZService.sendGjBatchMessage request) {
            return base.Channel.sendGjBatchMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendGjBatchMessageResponse> sendGjBatchMessageAsync(string account, string password, string sendDateTime, string destmobile, string msgText) {
            Maticsoft.Services.JZService.sendGjBatchMessage inValue = new Maticsoft.Services.JZService.sendGjBatchMessage();
            inValue.Body = new Maticsoft.Services.JZService.sendGjBatchMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            return ((Maticsoft.Services.JZService.BusinessService)(this)).sendGjBatchMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maticsoft.Services.JZService.validateUserResponse Maticsoft.Services.JZService.BusinessService.validateUser(Maticsoft.Services.JZService.validateUser request) {
            return base.Channel.validateUser(request);
        }
        
        public int validateUser(string account, string password) {
            Maticsoft.Services.JZService.validateUser inValue = new Maticsoft.Services.JZService.validateUser();
            inValue.Body = new Maticsoft.Services.JZService.validateUserBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            Maticsoft.Services.JZService.validateUserResponse retVal = ((Maticsoft.Services.JZService.BusinessService)(this)).validateUser(inValue);
            return retVal.Body.validateUserReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.validateUserResponse> Maticsoft.Services.JZService.BusinessService.validateUserAsync(Maticsoft.Services.JZService.validateUser request) {
            return base.Channel.validateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maticsoft.Services.JZService.validateUserResponse> validateUserAsync(string account, string password) {
            Maticsoft.Services.JZService.validateUser inValue = new Maticsoft.Services.JZService.validateUser();
            inValue.Body = new Maticsoft.Services.JZService.validateUserBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            return ((Maticsoft.Services.JZService.BusinessService)(this)).validateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maticsoft.Services.JZService.sendMessageResponse Maticsoft.Services.JZService.BusinessService.sendMessage(Maticsoft.Services.JZService.sendMessage request) {
            return base.Channel.sendMessage(request);
        }
        
        public int sendMessage(string account, string password, string destmobile, string msgText) {
            Maticsoft.Services.JZService.sendMessage inValue = new Maticsoft.Services.JZService.sendMessage();
            inValue.Body = new Maticsoft.Services.JZService.sendMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            Maticsoft.Services.JZService.sendMessageResponse retVal = ((Maticsoft.Services.JZService.BusinessService)(this)).sendMessage(inValue);
            return retVal.Body.sendMessageReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendMessageResponse> Maticsoft.Services.JZService.BusinessService.sendMessageAsync(Maticsoft.Services.JZService.sendMessage request) {
            return base.Channel.sendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendMessageResponse> sendMessageAsync(string account, string password, string destmobile, string msgText) {
            Maticsoft.Services.JZService.sendMessage inValue = new Maticsoft.Services.JZService.sendMessage();
            inValue.Body = new Maticsoft.Services.JZService.sendMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            return ((Maticsoft.Services.JZService.BusinessService)(this)).sendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maticsoft.Services.JZService.sendTimelyMessageResponse Maticsoft.Services.JZService.BusinessService.sendTimelyMessage(Maticsoft.Services.JZService.sendTimelyMessage request) {
            return base.Channel.sendTimelyMessage(request);
        }
        
        public int sendTimelyMessage(string account, string password, string sendDateTime, string destmobile, string msgText) {
            Maticsoft.Services.JZService.sendTimelyMessage inValue = new Maticsoft.Services.JZService.sendTimelyMessage();
            inValue.Body = new Maticsoft.Services.JZService.sendTimelyMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            Maticsoft.Services.JZService.sendTimelyMessageResponse retVal = ((Maticsoft.Services.JZService.BusinessService)(this)).sendTimelyMessage(inValue);
            return retVal.Body.sendTimelyMessageReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendTimelyMessageResponse> Maticsoft.Services.JZService.BusinessService.sendTimelyMessageAsync(Maticsoft.Services.JZService.sendTimelyMessage request) {
            return base.Channel.sendTimelyMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendTimelyMessageResponse> sendTimelyMessageAsync(string account, string password, string sendDateTime, string destmobile, string msgText) {
            Maticsoft.Services.JZService.sendTimelyMessage inValue = new Maticsoft.Services.JZService.sendTimelyMessage();
            inValue.Body = new Maticsoft.Services.JZService.sendTimelyMessageBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            return ((Maticsoft.Services.JZService.BusinessService)(this)).sendTimelyMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maticsoft.Services.JZService.sendMmsMessagesResponse Maticsoft.Services.JZService.BusinessService.sendMmsMessages(Maticsoft.Services.JZService.sendMmsMessages request) {
            return base.Channel.sendMmsMessages(request);
        }
        
        public int sendMmsMessages(string account, string password, string phones, string mmsString) {
            Maticsoft.Services.JZService.sendMmsMessages inValue = new Maticsoft.Services.JZService.sendMmsMessages();
            inValue.Body = new Maticsoft.Services.JZService.sendMmsMessagesBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.phones = phones;
            inValue.Body.mmsString = mmsString;
            Maticsoft.Services.JZService.sendMmsMessagesResponse retVal = ((Maticsoft.Services.JZService.BusinessService)(this)).sendMmsMessages(inValue);
            return retVal.Body.sendMmsMessagesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendMmsMessagesResponse> Maticsoft.Services.JZService.BusinessService.sendMmsMessagesAsync(Maticsoft.Services.JZService.sendMmsMessages request) {
            return base.Channel.sendMmsMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendMmsMessagesResponse> sendMmsMessagesAsync(string account, string password, string phones, string mmsString) {
            Maticsoft.Services.JZService.sendMmsMessages inValue = new Maticsoft.Services.JZService.sendMmsMessages();
            inValue.Body = new Maticsoft.Services.JZService.sendMmsMessagesBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.phones = phones;
            inValue.Body.mmsString = mmsString;
            return ((Maticsoft.Services.JZService.BusinessService)(this)).sendMmsMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maticsoft.Services.JZService.gxmtResponse Maticsoft.Services.JZService.BusinessService.gxmt(Maticsoft.Services.JZService.gxmt request) {
            return base.Channel.gxmt(request);
        }
        
        public int gxmt(string account, string password, string sendDateTime, string destmobiles, string msgTexts) {
            Maticsoft.Services.JZService.gxmt inValue = new Maticsoft.Services.JZService.gxmt();
            inValue.Body = new Maticsoft.Services.JZService.gxmtBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobiles = destmobiles;
            inValue.Body.msgTexts = msgTexts;
            Maticsoft.Services.JZService.gxmtResponse retVal = ((Maticsoft.Services.JZService.BusinessService)(this)).gxmt(inValue);
            return retVal.Body.gxmtReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.gxmtResponse> Maticsoft.Services.JZService.BusinessService.gxmtAsync(Maticsoft.Services.JZService.gxmt request) {
            return base.Channel.gxmtAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maticsoft.Services.JZService.gxmtResponse> gxmtAsync(string account, string password, string sendDateTime, string destmobiles, string msgTexts) {
            Maticsoft.Services.JZService.gxmt inValue = new Maticsoft.Services.JZService.gxmt();
            inValue.Body = new Maticsoft.Services.JZService.gxmtBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobiles = destmobiles;
            inValue.Body.msgTexts = msgTexts;
            return ((Maticsoft.Services.JZService.BusinessService)(this)).gxmtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maticsoft.Services.JZService.getUserInfoResponse Maticsoft.Services.JZService.BusinessService.getUserInfo(Maticsoft.Services.JZService.getUserInfo request) {
            return base.Channel.getUserInfo(request);
        }
        
        public string getUserInfo(string account, string password) {
            Maticsoft.Services.JZService.getUserInfo inValue = new Maticsoft.Services.JZService.getUserInfo();
            inValue.Body = new Maticsoft.Services.JZService.getUserInfoBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            Maticsoft.Services.JZService.getUserInfoResponse retVal = ((Maticsoft.Services.JZService.BusinessService)(this)).getUserInfo(inValue);
            return retVal.Body.getUserInfoReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.getUserInfoResponse> Maticsoft.Services.JZService.BusinessService.getUserInfoAsync(Maticsoft.Services.JZService.getUserInfo request) {
            return base.Channel.getUserInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maticsoft.Services.JZService.getUserInfoResponse> getUserInfoAsync(string account, string password) {
            Maticsoft.Services.JZService.getUserInfo inValue = new Maticsoft.Services.JZService.getUserInfo();
            inValue.Body = new Maticsoft.Services.JZService.getUserInfoBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            return ((Maticsoft.Services.JZService.BusinessService)(this)).getUserInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maticsoft.Services.JZService.sendAudioResponse Maticsoft.Services.JZService.BusinessService.sendAudio(Maticsoft.Services.JZService.sendAudio request) {
            return base.Channel.sendAudio(request);
        }
        
        public int sendAudio(string account, string password, string sendDateTime, string destmobile, string msgText, string srcMobile) {
            Maticsoft.Services.JZService.sendAudio inValue = new Maticsoft.Services.JZService.sendAudio();
            inValue.Body = new Maticsoft.Services.JZService.sendAudioBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            inValue.Body.srcMobile = srcMobile;
            Maticsoft.Services.JZService.sendAudioResponse retVal = ((Maticsoft.Services.JZService.BusinessService)(this)).sendAudio(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendAudioResponse> Maticsoft.Services.JZService.BusinessService.sendAudioAsync(Maticsoft.Services.JZService.sendAudio request) {
            return base.Channel.sendAudioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Maticsoft.Services.JZService.sendAudioResponse> sendAudioAsync(string account, string password, string sendDateTime, string destmobile, string msgText, string srcMobile) {
            Maticsoft.Services.JZService.sendAudio inValue = new Maticsoft.Services.JZService.sendAudio();
            inValue.Body = new Maticsoft.Services.JZService.sendAudioBody();
            inValue.Body.account = account;
            inValue.Body.password = password;
            inValue.Body.sendDateTime = sendDateTime;
            inValue.Body.destmobile = destmobile;
            inValue.Body.msgText = msgText;
            inValue.Body.srcMobile = srcMobile;
            return ((Maticsoft.Services.JZService.BusinessService)(this)).sendAudioAsync(inValue);
        }
    }
}
