//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Admin.SNS.ProductSources {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtWebSiteName;
		protected global::System.Web.UI.WebControls.TextBox txtWebSiteUrl;
		protected global::System.Web.UI.WebControls.TextBox txtWebSiteLogo;
		protected global::System.Web.UI.WebControls.TextBox txtCategoryTags;
		protected global::System.Web.UI.WebControls.TextBox txtPriceTags;
		protected global::System.Web.UI.WebControls.TextBox txtImagesTag;
		protected global::System.Web.UI.WebControls.TextBox txtStatus;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
